import { StartTimeDto } from '../StartTimes/StartTimeDto.model';
import { LeaveTimeDto } from '../TimeToLeaves/LeaveTimeDto.model';
import { ReceiveCardAddressDto } from '../ReceiveCardLocations/ReceiveCardAddressDto.model';
import { PrintStatus } from '../Enums/PrintStatus.enum';
import { ReceiveCardStatus } from '../Enums/ReceiveCardStatus.enum';
import { PositionType } from '../Enums/PositionType.enum';
import { RegisterRole } from '../Enums/RegisterRole.enum';
import { ContactStatusType } from '../Enums/ContactStatusType.enum';
import { MoveType } from '../Enums/MoveType.enum';
import { DepartmentDto } from '../Departments/DepartmentDto.model';
import { RegisterType } from '../Enums/RegisterType.enum';
import { EventRegistryPageDto } from '../EventRegistryPages/EventRegistryPageDto.model';
import { MemberDto } from '../Members/MemberDto.model';
import { DepartmentDetailDto } from '../DepartmentDetails/DepartmentDetailDto.model';
import { AreaDto } from '../Areas/AreaDto.model';
import { CarBookingType } from '../Enums/CarBookingType.enum';
import { EventDto } from '../EventDto.model';
import { ClothingSize } from '../Enums/ClothingSize.enum';
import { StatusType } from '../Enums/StatusType.enum';
import { GroupDto } from '../Groups/GroupDto.model';
import { CertificateRegistry } from '../Enums/CertificateRegistry.enum';

export type EventRegistryDto = {
  id?: string;
  memberId?: string;
  eventId?: number;
  code?: string;
  note?: string;
  startPlaneCode?: string;
  returnPlaneCode?: string;
  otherLeaveAddress?: string;
  otherStartAddress?: string;
  eventRegistryPageId?: string;
  area?: AreaDto;
  isArrived: boolean;
  event?: EventDto;
  group?: GroupDto;
  moveType?: MoveType;
  member?: MemberDto;
  areaId?: number;
  endDate?: string;
  groupId?: number;
  position?: PositionType;
  leaderId?: string;
  startDate?: string;
  arrivedAt?: Date;
  startTimeId?: number;
  leaveTimeId?: number;
  printStatus?: PrintStatus;
  registerRole?: RegisterRole;
  assignStatus?: StatusType;
  otherStartTime?: string;
  otherLeaveTime?: string;
  receiveCardStatus?: ReceiveCardStatus;
  departmentDetailId?: number;
  receiveCardAddressId?: number;
  startTime?: StartTimeDto;
  leaveTime?: LeaveTimeDto;
  registerType?: RegisterType;
  expDepartments?: DepartmentDto[];
  wishDepartment?: DepartmentDto;
  leader?: EventRegistryDto;
  contactStatus?: ContactStatusType;
  departmentDetail?: DepartmentDetailDto;
  eventRegistryPage?: EventRegistryPageDto;
  receiveCardAddress?: ReceiveCardAddressDto;
  // thêm field
  carBookingType?: CarBookingType;
  clothingSize?: ClothingSize;
  // certificateRegistry?: boolean;
  certificateRegistry?: CertificateRegistry;
  companyNameVIE?: string;
  companyNameEN?: string;
};
