import { MoveType } from '../Enums/MoveType.enum';
import { PositionType } from '../Enums/PositionType.enum';
import { RegisterType } from '../Enums/RegisterType.enum';
import { CarBookingType } from '../Enums/CarBookingType.enum';
import { ClothingSize } from '../Enums/ClothingSize.enum';
import { CertificateRegistry } from '../Enums/CertificateRegistry.enum';

export type UpSertEventRegistryDto = {
  memberId?: string;
  eventId?: number;
  note?: string;
  startPlaneCode?: string;
  returnPlaneCode?: string;
  eventRegistryPageId?: string;
  moveType?: MoveType;
  endDate?: string;
  position?: PositionType;
  leaderId?: string;
  startDate?: string;
  startAddressId?: number;
  startTimeId?: number;
  leaveAddressId?: number;
  leaveTimeId?: number;
  otherStartTime?: string;
  otherLeaveTime?: string;
  receiveCardAddressId?: number;
  registerType?: RegisterType;
  expDepartmentIds?: number[];
  wishDepartmentId?: number[];
  otherStartAddress?: string;
  otherLeaveAddress?: string;
  type?: string;
  ctnId?: string;
  ctnGroupId?: string;
  // thêm field
  carBookingType?: CarBookingType;
  clothingSize?: ClothingSize;
  certificateRegistry?: boolean;
  // certificateRegistry?: CertificateRegistry;
  companyNameVIE?: string;
  companyNameEN?: string;
  registeredDays?: number[];
};
