import { TimeToStartDto } from '../TimeToStarts/TimeToStartDto.model';
import { TimeToLeaveDto } from '../TimeToReturns/TimeToLeaveDto.model';
import { ReceiveCardLocationDto } from '../ReceiveCardLocations/ReceiveCardLocationDto.model';
import { PrintStatus } from '../Enums/PrintStatus.enum';
import { ReceiveCardStatus } from '../Enums/ReceiveCardStatus.enum';
import { ContactStatusType } from '../Enums/ContactStatusType.enum';
import { DepartmentResponse } from '../Departments/DepartmentResponse.model';
import { GreatCeremonyDto } from '../GreatCeremonyDto.dto';
import { MemberResponseDto } from '../Members/MemberResponse.dto';
import { DepartmentDetailDto } from '../DepartmentDetails/DepartmentDetailDto.model';
import { AreaDto } from '../Areas/AreaDto.model';
import { GroupDto } from '../Groups/Group.dto';

export type DKDaiLeDto = {
  id: number;
  maSo: string;
  ghiChu: string;
  position: string;
  maChuyenBayVe: string;
  maChuyenBayDen: string;
  positionInGroup: string;
  diaDiemTroVeKhac: string;
  thoiDiemVeChuaKhac: string;
  greatCeremonyRegistrationId: string;
  greatCeremonyRegistrationName: string;
  area: AreaDto;
  group: GroupDto;
  member: MemberResponseDto;
  areaId: number;
  groupId: number;
  memberId: number;
  trangThai: ContactStatusType;
  createdBy: number;
  createdAt: string;
  updatedBy: number;
  updatedAt: string;
  ngayBatDau: string;
  trangThaiIn: PrintStatus;
  ngayKetThuc: string;
  idNoiNhanThe: number;
  idBanKinhNghiem: number;
  idBanNguyenVong: number;
  greatCeremonyId: number;
  idThoiDiemVeChua: number;
  trangThaiNhanThe: ReceiveCardStatus;
  thoiGianVeChuaKhac: string;
  departmentDetailId: number;
  thoiGianRoiChuaKhac: string;
  idThoiDiemVeNoiXuatPhat: number;
  thoiDiemVeChua: TimeToStartDto;
  thoiDienRoiChua: TimeToLeaveDto;
  greatCeremony: GreatCeremonyDto;
  banKinhNghiem: DepartmentResponse;
  banNguyenVong: DepartmentResponse;
  departmentDetail: DepartmentDetailDto;
  noiNhanThe: ReceiveCardLocationDto;
};
